name: CI

on: 
  push:
    branches: [ "main" ]
  pull_request: 
    branch: [ "main" ] 

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: Pull repo
    uses: actions/checkout@v4
    - name: print hello
      run: echo "Hello"